name: Deploy to GitHub Pages and Netlify

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1' # add the node version

      - name: Install dependencies
        working-directory: ./  # for netlify Set the working directory to project root
        run: npm install

      - name: Build
        working-directory: ./ # for netlify
        run: npm run build

        # Deploy to Netlify
      - name: Deploy to Netlify
        if: success()  # Only deploy to Netlify if build is successful
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Netlify authentication token
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # Netlify site ID
        run: |
          npx netlify deploy --prod  # Deploy to Netlify production environment

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # add name of secret you created in place of GH_TOKEN
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

          # Initialize a new branch for deployment
          git checkout --orphan gh-pages

          # Remove all files in the current directory
          git rm -rf .

          # Move built files to the root of the gh-pages branch
          mv -f build/* .

          # Remove the build directory
          rm -rf build

          # Add all files to git
          git add -A

          # Commit the changes
          git commit -m "Deployed using GitHub Actions"

          # Push the changes to the gh-pages branch
          git push -f origin gh-pages
      
      